services:
  execution-init:
    container_name: gas-execution-client-sync
    image: ${EC_IMAGE_VERSION}
    networks:
    - gas
    volumes:
    - ${EC_DATA_DIR}:/var/lib/goethereum
    - ${EC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
    - ${GENESIS_PATH}:/tmp/genesis/genesis.json
    entrypoint: geth --cache 4096 init --datadir=/var/lib/goethereum /tmp/genesis/genesis.json
  # Extend the execution service from execution.yaml and add dependency
  execution:
    extends:
      file: docker-compose-second.yaml
      service: execution
    depends_on:
      execution-init:
        condition: service_completed_successfully
networks:
  gas:
    name: gas-network
