services:
  execution:
    user: "root:root"
    stop_grace_period: 30m
    container_name: gas-execution-client
    restart: unless-stopped
    image: ${EC_IMAGE_VERSION:-erigontech/erigon:v3.0.0-rc1}
    networks:
    - gas
    volumes:
    - ${EC_DATA_DIR:-./erigon-data}:/var/lib/erigon
    - ${EC_JWT_SECRET_PATH:-/tmp/jwtsecret}:/tmp/jwt/jwtsecret
    ports:
    - "30303:30303/tcp"
    - "30303:30303/udp"
    - "8008:8008/tcp"
    - "8545:8545"
    - "8551:8551"
    command:
    - --private.api.addr=0.0.0.0:9090
    - --nat=any
    - --http
    - --http.addr=0.0.0.0
    - --http.port=8545
    - --http.vhosts=*
    - --http.corsdomain=*
    - --http.api=web3,eth,net,engine
    - --txpool.disable
    - --chain=${NETWORK:-holesky}
    - --authrpc.addr=0.0.0.0
    - --authrpc.port=8551
    - --authrpc.vhosts=*
    - --authrpc.jwtsecret=/tmp/jwt/jwtsecret
    - --datadir=/var/lib/erigon
    - --healthcheck
    - --metrics
    - --metrics.addr=0.0.0.0
    - --metrics.port=8008
    - --db.size.limit=2GB
    - --externalcl
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
networks:
  gas:
    name: gas-network
