services:
  execution-init:
    user: "root:root"
    container_name: gas-execution-client-sync
    image: ${EC_IMAGE_VERSION:-erigontech/erigon:v3.0.0-rc1}
    networks:
    - gas
    volumes:
    - ${EC_DATA_DIR:-./erigon-data}:/var/lib/erigon
    - ${EC_JWT_SECRET_PATH:-/tmp/jwtsecret}:/tmp/jwt/jwtsecret
    - ${GENESIS_PATH:-/tmp/genesis.json}:/tmp/genesis/genesis.json
    entrypoint: erigon init --datadir=/var/lib/erigon /tmp/genesis/genesis.json
  
  # Extend the execution service from execution.yaml and add dependency
  execution:
    extends:
      file: docker-compose-second.yaml
      service: execution
    depends_on:
      execution-init:
        condition: service_completed_successfully

networks:
  gas:
    name: gas-network
